declare var cv: any;
declare const video: HTMLVideoElement;
declare const canvasOutput: HTMLCanvasElement;
declare const startBtn: HTMLButtonElement;
declare const stopBtn: HTMLButtonElement;
declare const screenshotBtn: HTMLButtonElement;
declare const loadingOverlay: HTMLDivElement;
declare const startPrompt: HTMLDivElement;
declare const threshold1Input: HTMLInputElement;
declare const threshold2Input: HTMLInputElement;
declare const val1Display: HTMLSpanElement;
declare const val2Display: HTMLSpanElement;
declare let stream: MediaStream | null;
declare let processingInterval: number | null;
declare let isOpenCvReady: boolean;
declare let isProcessing: boolean;
declare let threshold1: number;
declare let threshold2: number;
declare function toggleUIState(processing: boolean): void;
declare function startCamera(): Promise<void>;
declare function waitingForVideoLoad(): void;
declare function startProcessing(): void;
declare function stopCamera(): void;
declare function takeScreenshot(): void;
